CREATE USER 'metabase101'@'%' IDENTIFIED VIA mysql_native_password USING 'your-secured-password';
GRANT USAGE ON *.* TO 'metabase101'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `metabase101`;
GRANT ALL PRIVILEGES ON `metabase101`.* TO 'metabase101'@'%';
GRANT ALL PRIVILEGES ON `metabase101\_%`.* TO 'metabase101'@'%';
