CREATE TABLE `orders` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`User ID` INT(11) NULL DEFAULT NULL,
	`Product ID` INT(11) NULL DEFAULT NULL,
	`Subtotal` FLOAT NULL DEFAULT NULL,
	`Tax` FLOAT NULL DEFAULT NULL,
	`Total` FLOAT NULL DEFAULT NULL,
	`Discount` FLOAT NULL DEFAULT NULL,
	`Created At` TIMESTAMP NULL DEFAULT NULL,
	`Quantity` FLOAT NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;


